coinhall/yacar

- .github/workflows/ci.yml
tested and working:
workflow run: https://github.com/yusufaine/test-yacar/actions/runs/3787839292
workflow file (diff): https://github.com/yusufaine/test-yacar/commit/04d91b8d6b4e084282d2022323c943259bc0898f
> ci: format on merge to main

- terra/binary.json
- terra/contract.json
Add codes/binaries and contracts data for Terra from our/Alles' Cosmos Registry that is missing from yacar's.
> add terra codes and contracts

- terra/asset.json
added 
sayve terra1xp9hrhthzddnl7j5du83gqqr4wmdjm5t0guzg9jp6jwrtpukwfjsjgy4f3 
and 
xSayve terra16zc783wt2w5lvlt9u4as977lt39c3se427akkenrzyax5vtde70qa89ukv
> added sayve and xsayve

- terra/asset.json
> Trump Dao Token

- terraclassic/asset.json
> renamed sayve to sayvec for classic

- terra/asset.json
- terra/entity.json
add circulating supply info for trump token
> add circulating supply

- terra/asset.json
updated metadata for the CUB token: added icon and entity
> updated metadata for the CUB token

- terra/account.json
https://www.binance.com/en/support/announcement/binance-to-make-changes-to-the-burning-of-terra-classic-lunc-trading-fees-4769eab576c4479eaa14adc1eb587226
> add binance wallets

- terra/asset.json
- terra/entity.json
- fix: Lion Cub DAO
- fix: format
> fix: Lion Cub DAO entity

- terra/asset.json
add $ORNE circulating supply and cmc.
> Update asset.json - add $ORNE circulating supply and cm

- juno/asset.json
- kujira/asset.json
- osmosis/asset.json
- terra/asset.json
- terraclassic/asset.json
- Add 1 items
- chore: fix issue
- chore: change ATOM lcd
> fix: ATOM circ supply LCD endpoint

- juno/asset.json
- kujira/asset.json
- osmosis/asset.json
- terra/asset.json
- terraclassic/asset.json
- chore: update ATOM
- chore: update CRO
- chore: update STRD and lsd assets
- chore: update ampLUNA
- chore: update JUNO
- chore: update KUJI
- chore: update LUNA
- chore: update OSMO
- chore: update missed assets
> fix: prefer cosmos directory for lcd

- terra/asset.json
- terra/entity.json
> chore: GEM DAO info

- terra/asset.json
Clean up PR for #1501 - #1503 made by @egrassy
> chore: TheOnlyOne asset update

- .github/scripts/cmd/sorter/sorter.go
- .github/scripts/cmd/validator/validator.go
- .github/scripts/cmd/yacar_ci.go
- .github/scripts/go.mod
- .github/scripts/go.sum
- .github/scripts/internal/walker/walker.go
- README.md
1. `validator` has been updated to ensure that `*_supply` and `*_api` are mutually exclusive
2. change `log.Panic()` to just `panic()` so that Github Actions logs are more readable
> feat: support static/dynamic supply

- terra/asset.json
xxx token supply data completed
> circulating-supply and  total_supply xxx token

- terra/asset.json
* update from stale branch https://github.com/coinhall/yacar/pull/1598
> fix: xxx icon change

- terraclassic/asset.json
- terraclassic/pool.json
LUNC Warriors NFT is a NFT art project with corresponding CW20 token on Terra Classic. Added:
- pool contract address
- token contract address
- LP token address
- logo
I hereby politely ask to add these assets to the terraclassic assets. Thank you for your support.
Humbly,
Till
> Add LUNW Token Assets

- terraclassic/asset.json
- terraclassic/entity.json
Closes #1722 by [lunc808](https://github.com/lunc808) due to failing CI
> chore: FRG info

- terra/asset.json
> PhoenixDAO_Update asset.json

- terraclassic/asset.json
- terraclassic/entity.json
> chore: link garudax entity

- terra/asset.json
> Update asset.json Bitz DAO Token

- migaloo/asset.json
RAC is currently at max circulating supply. 
Let us know if you need anything else
> Add RAC circulating supply

- terra/asset.json
> chore: egrassy queen asset

- terra/asset.json
Circulating and total supply are fixed for now in [Phase 1](https://docs.ura.xyz/ura/start-here/launch-details#phase-1-the-community-farmdrop-currently-active). We will update this repo again with the API endpoints once emissions starts nearer to phase 2. Many thanks.
> add URA circ and total supply

- neutron/asset.json
> fix: wstETH and wETH decimals

- osmosis/asset.json
> fix: wBNB decimals

- injective/pool.json
injective 0xbf94d932d1463959badee52ffbeb2eeeeeda750e655493e909ced540c375a277 `orderbook` -> `orderbook/perp`
> fix: wrong type for pool

- osmosis/asset.json
circ_supply and total_supply are in wei unit
> Update "FX" token circ_supply_api, total_supply_api, coinmarket and coingecko url

- kujira/asset.json
- kujira/entity.json
> fix: fuzion info

- injective/asset.json
added suplly information for $LABS coin
> add supply information for $LABS coin

- injective/asset.json
https://github.com/coinhall/yacar/pull/2412#issuecomment-1861875254
> fix: ginger supply

- injective/asset.json
> Update INJINU info

- sei/asset.json
400M was error typo'd for circ amount, should be 600M
> Update asset.json (SEIYAN supply fix)

- injective/asset.json
Add karate native coin icon url
> Add karate native token icon

- .github/workflows/ci.yml
This reverts commit 2cd315c6dcdb9c67c784d40f6533c3c99da103f0.
> Revert "chore: CI improvement (#3514)"

- sei/asset.json
> Update Sensei Dog Icon

- sei/asset.json
burn happened at ABF921AE058CD78148C4CAD7C5D0C092CED83499A04FF00BC165BCCA9899A46F
> reflect seiyaninu tokens after burn

- sei/asset.json
> add seimoyed

- sei/asset.json
Mistakenly put number with 6 decimal places included
> Updating SEIMOYED supply

- sei/asset.json
- sei/entity.json
Astroport token listing: https://github.com/astroport-fi/astroport-token-lists/pull/171
> Add POPEYE

- terra/asset.json
The very real & very rich man himself asked me to get the token logo onto Coinhall
> Add ARMANI token icon

- .vscode/settings.json
- terraclassic/asset.json
> Fix *.png links

- sei/asset.json
- sei/entity.json
> SEIMOON TOKEN INFO UPDATE

- migaloo/asset.json
The GUPPY logo added to asset.json
> GUPPY logo added on migaloo asset list

- terra/asset.json
- terra/entity.json
The very real & very rich man himself asked me to add socials to his precious token
> Add ARMANI entity & socials

- sei/asset.json
> seitoad logo update

- sei/asset.json
- sei/entity.json
SeiDragon Social And Logo Update
> SeiDragon Social And Logo Update

- injective/asset.json
- injective/entity.json
We added total supply,  circle supply of SNOWY token and social links for community
> update information for SNOWY

- injective/asset.json
> Add ExtraVirginOliveInu Data

- sei/asset.json
Token icon updated.
coming soon seisino launch 100x your sei
> DOJO Token Icon updated! 

- terra/asset.json
add verification seul & xseul token
> Update asset.json 

- sei/asset.json
- sei/entity.json
add SeiWhale socials to entity.json and update asset.json
> update SeiWhale socials

- migaloo/asset.json
- migaloo/entity.json
Ophir Logo, Twitter and Website added
> Ophir Logo, Twitter and Website added

- injective/asset.json
- injective/entity.json
> Revert "Dojoswap socials"

- injective/asset.json
> Revert "[bot][injective] add 6 assets"

- terra/asset.json
> Revert "[bot][terra] add 2 assets"

- migaloo/asset.json
> Revert "[bot][migaloo] add 1 assets"

- terra/asset.json
change total supply and circ supply of xxx token
> change total supply and circ supply of xxx token

- injective/asset.json
> Revert "[bot][injective] add 7 assets"

- terra/asset.json
- terra/entity.json
- Remove obsolete twitter account
- Add "website" (Enterprise page)
- Add Discord invite
- Add total_supply_api
> Update GEM token + entity

- sei/entity.json
As the SeiWhale token is now community driven, the team and infrastructure is re-organizing.
> Update website and discord for seiwhale token

- injective/asset.json
Asset ID: `factory/inj1maeyvxfamtn8lfyxpjca8kuvauuf2qeu6gtxm3/Talis`
Decimals: `0 -> 6`
> update decimals of TALIS

- terra/asset.json
- terra/entity.json
> Add Bitmos logo and socials

- migaloo/asset.json
- osmosis/asset.json
Add SHARK token for Shark Protocol
> Add SHARK token for Shark Protocol

- terraclassic/asset.json
- terraclassic/entity.json
> added MBA info

- terraclassic/asset.json
- terraclassic/entity.json
> Revert "[bot][terraclassic] chore: update DTH asset metadata"

- osmosis/asset.json
- osmosis/entity.json
Add "Mad Scientist" into the entity.json file. Also added entity to the asset json file.
> add mad scientist entity

- migaloo/asset.json
- migaloo/entity.json
- osmosis/asset.json
- osmosis/entity.json
> Add GRAC token for Racoon.Bet

- injective/asset.json
> add babyClon info

- terra/asset.json
> update xxx token info

- injective/asset.json
- injective/entity.json
This reverts commit 4a885ccf9af439eaf3b005c99abffa631fcef772.
> Revert "[bot][injective] chore: update MINJ asset metadata (#12773)"

- terra/asset.json
> update total supply

- .gitignore
- terraclassic/asset.json
- terraclassic/entity.json
added new terraclassic token for Memecoin Madness
> added LVBNS

- terra/asset.json
another burn xxx sir pls update
> xxx total suplay update

- terra/asset.json
Sayve tokens have been burned and continue to be burned, added total supply from url
> Update asset.json with total supply
